# 1 mục tiêu 
- Sau khi hoàn thành bài thực hành, sinh viên có thể:
- Tạo, kiểm tra và thao tác với Tensor trong PyTorch.
- Thực hiện indexing, slicing, reshape và các phép toán ma trận trên Tensor.
- Sử dụng các hàm thống kê cơ bản trên Tensor.
- Hiểu cơ chế automatic differentiation (autograd) và vai trò của gradient.
- Sử dụng optimizer để giải bài toán tối ưu rõ ràng bằng Gradient Descent.
- PyTorch cung cấp hai khả năng nền tảng: tính toán Tensor và automatic differentiation.

# 2. Bài tập thực hành
## Bài 1. Tạo Tensor cơ bản
### Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [28]:
import torch
a =torch.tensor(
    [[1,2,3],
     [4,5,6]],
    dtype = torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


#### Yêu cầu: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

- kích thước:(2,3) 
- số chiều: 2 chiều
- kiểu dữ liệu: torch.int32

## Bài 2. Tạo các Tensor thường dùng
### Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [29]:
import torch
a = torch.rand(3,4)
b = torch.randn(3,4)
c = torch.zeros(2,3)
d = torch.ones(2,3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)


tensor([[0.3325, 0.9070, 0.7947, 0.2296],
        [0.4032, 0.0103, 0.4748, 0.4207],
        [0.7067, 0.2956, 0.2685, 0.4865]])
tensor([[ 0.4405,  1.3007, -0.5694,  0.5822],
        [-0.6870,  0.4300,  0.2899, -0.5717],
        [ 2.2849, -0.7444,  1.0004, -0.2565]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#### Yêu cầu:
- Nhận xét sự khác nhau giữa torch.rand() và torch.randn().
- Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

- sự khác nhau torch.rand()tạo bảng chứ số [0,1] còn torch.randn() với số ngâu nhiên quanh 0 có âm và dương

In [30]:
import torch
f = torch.full((5,5), 10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3. Kiểm tra thông tin Tensor
### Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [31]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


#### yêu cầu:Yêu cầu: Giải thích ý nghĩa của torch.Size([2, 3, 4]).
- torch.Size([2, 3, 4]) cho biết tersor a có 3 chiều và kích thước lần lượt 2x3x4 nghĩa tersor có 2 khối, 3 hàng, 4 cột

## Bài 4. Slicing và Indexing
### Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [32]:
import torch
a = torch.randn(3, 4, 5)
print("original tensor:")
print(a)
print("tensor a[1]:")
print(a[1])
print("tensor a[1:, 2:4]:")
print(a[1:, 2:4])


original tensor:
tensor([[[-0.2392,  1.5452, -0.0599, -1.3565,  1.8896],
         [ 0.7163, -0.0279, -0.0292, -0.0621,  0.3259],
         [ 0.0675, -0.5154, -2.0013,  1.0972, -1.5246],
         [ 0.1540, -0.6060, -1.0035, -1.7583,  1.5572]],

        [[ 0.7786,  0.7285, -0.5888,  2.0147,  0.5040],
         [-0.3154, -0.8790,  0.4210,  1.9096, -0.0935],
         [ 0.3506, -0.0238, -0.3993,  1.3271,  0.4323],
         [ 0.3090, -1.2232,  2.1694,  0.8107,  0.6668]],

        [[ 0.3763,  0.2427,  1.0556, -1.1662, -0.4858],
         [-0.4933, -0.0989,  0.9258, -0.5643,  0.7524],
         [ 0.2037,  0.0905,  0.4423, -0.5992,  1.6125],
         [-1.3971, -0.4179, -1.7167, -0.6007, -0.6098]]])
tensor a[1]:
tensor([[ 0.7786,  0.7285, -0.5888,  2.0147,  0.5040],
        [-0.3154, -0.8790,  0.4210,  1.9096, -0.0935],
        [ 0.3506, -0.0238, -0.3993,  1.3271,  0.4323],
        [ 0.3090, -1.2232,  2.1694,  0.8107,  0.6668]])
tensor a[1:, 2:4]:
tensor([[[ 0.3506, -0.0238, -0.3993,  1.3271,  0.432

### Yêu cầu:
- Cho biết shape của a[1] và a[1:, 2:4].
- Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

- a[1].shape = [4,5], a[1:, 2:4] = [2,2,5]
- note:
        a[1]       # Indexing
        a[1:3]     # Slicing
        a[-2:]     # Slicing

In [33]:
print(a[:,:,-2:])

tensor([[[-1.3565,  1.8896],
         [-0.0621,  0.3259],
         [ 1.0972, -1.5246],
         [-1.7583,  1.5572]],

        [[ 2.0147,  0.5040],
         [ 1.9096, -0.0935],
         [ 1.3271,  0.4323],
         [ 0.8107,  0.6668]],

        [[-1.1662, -0.4858],
         [-0.5643,  0.7524],
         [-0.5992,  1.6125],
         [-0.6007, -0.6098]]])


## Bài 5. Reshape và Flatten
### Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [35]:
import torch
a = torch.randn(3, 4)
print("original:")
print(a)
print("\nFlatten: ")
print(a.ravel())
print("\nReshape to 3 x 2 x 2: ")
print(a.reshape(3,2,2))

original:
tensor([[ 0.6404, -1.0792, -1.6060,  0.8194],
        [ 0.6458, -1.7727,  1.2736, -1.4466],
        [-1.4139, -2.1120,  0.5440,  2.0597]])

Flatten: 
tensor([ 0.6404, -1.0792, -1.6060,  0.8194,  0.6458, -1.7727,  1.2736, -1.4466,
        -1.4139, -2.1120,  0.5440,  2.0597])

Reshape to 3 x 2 x 2: 
tensor([[[ 0.6404, -1.0792],
         [-1.6060,  0.8194]],

        [[ 0.6458, -1.7727],
         [ 1.2736, -1.4466]],

        [[-1.4139, -2.1120],
         [ 0.5440,  2.0597]]])


#### Yêu cầu:
- Kiểm tra số phần tử trước và sau khi reshape.
- Thử reshape Tensor thành kích thước 2 × 6.

#### Trả lời
-Số phần tử trước và sau khi reshape vẫn giống nhau là 12 phần tử. Reshape chỉ thay đổi shape/cách tổ chức dữ liệu, không làm thay đổi số lượng phần tử.

In [37]:
print("reshape to 2 x 6")
print(a.reshape(2,6))

reshape to 2 x 6
tensor([[ 0.6404, -1.0792, -1.6060,  0.8194,  0.6458, -1.7727],
        [ 1.2736, -1.4466, -1.4139, -2.1120,  0.5440,  2.0597]])


## Bài 6. Phép toán và nhân ma trận
### Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [ ]:
import torch
a = torch.randn(2,3)
b = torch.randn(2,3)
print("a:")
print(a)
print("b:")
print(b)
print("\n a+b")
print(a+b)
print("\n a*b")
print(a*b)
print("\n a/b")
print(a/b)
print("\n a^2")
print(a**2)
print("\nMatrix multiplication: ")
print(a @ b.T)

a:
tensor([[ 1.2982, -1.2468,  0.7220],
        [ 0.7830,  0.9333,  0.7290]])
b:
tensor([[ 0.3751, -1.8855, -1.6177],
        [-0.4030,  1.4676, -1.2963]])

 a+b
tensor([[ 1.6733, -3.1324, -0.8957],
        [ 0.3800,  2.4009, -0.5673]])

 a/b
tensor([[ 3.4612,  0.6613, -0.4463],
        [-1.9428,  0.6360, -0.5624]])

 a^2
tensor([[1.6854, 1.5546, 0.5213],
        [0.6131, 0.8711, 0.5315]])

Matrix multiplication: 
tensor([[ 1.6699, -3.2890],
        [-2.6454,  0.1091]])
