# 1 mục tiêu 
- Sau khi hoàn thành bài thực hành, sinh viên có thể:
- Tạo, kiểm tra và thao tác với Tensor trong PyTorch.
- Thực hiện indexing, slicing, reshape và các phép toán ma trận trên Tensor.
- Sử dụng các hàm thống kê cơ bản trên Tensor.
- Hiểu cơ chế automatic differentiation (autograd) và vai trò của gradient.
- Sử dụng optimizer để giải bài toán tối ưu rõ ràng bằng Gradient Descent.
- PyTorch cung cấp hai khả năng nền tảng: tính toán Tensor và automatic differentiation.

# 2. Bài tập thực hành
## Bài 1. Tạo Tensor cơ bản
### Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

In [28]:
import torch
a =torch.tensor(
    [[1,2,3],
     [4,5,6]],
    dtype = torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


#### Yêu cầu: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

- kích thước:(2,3) 
- số chiều: 2 chiều
- kiểu dữ liệu: torch.int32

## Bài 2. Tạo các Tensor thường dùng
### Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [29]:
import torch
a = torch.rand(3,4)
b = torch.randn(3,4)
c = torch.zeros(2,3)
d = torch.ones(2,3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)


tensor([[0.3325, 0.9070, 0.7947, 0.2296],
        [0.4032, 0.0103, 0.4748, 0.4207],
        [0.7067, 0.2956, 0.2685, 0.4865]])
tensor([[ 0.4405,  1.3007, -0.5694,  0.5822],
        [-0.6870,  0.4300,  0.2899, -0.5717],
        [ 2.2849, -0.7444,  1.0004, -0.2565]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#### Yêu cầu:
- Nhận xét sự khác nhau giữa torch.rand() và torch.randn().
- Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

- sự khác nhau torch.rand()tạo bảng chứ số [0,1] còn torch.randn() với số ngâu nhiên quanh 0 có âm và dương

In [30]:
import torch
f = torch.full((5,5), 10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3. Kiểm tra thông tin Tensor
### Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

In [31]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


#### yêu cầu:Yêu cầu: Giải thích ý nghĩa của torch.Size([2, 3, 4]).
- torch.Size([2, 3, 4]) cho biết tersor a có 3 chiều và kích thước lần lượt 2x3x4 nghĩa tersor có 2 khối, 3 hàng, 4 cột

## Bài 4. Slicing và Indexing
### Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [32]:
import torch
a = torch.randn(3, 4, 5)
print("original tensor:")
print(a)
print("tensor a[1]:")
print(a[1])
print("tensor a[1:, 2:4]:")
print(a[1:, 2:4])


original tensor:
tensor([[[-0.2392,  1.5452, -0.0599, -1.3565,  1.8896],
         [ 0.7163, -0.0279, -0.0292, -0.0621,  0.3259],
         [ 0.0675, -0.5154, -2.0013,  1.0972, -1.5246],
         [ 0.1540, -0.6060, -1.0035, -1.7583,  1.5572]],

        [[ 0.7786,  0.7285, -0.5888,  2.0147,  0.5040],
         [-0.3154, -0.8790,  0.4210,  1.9096, -0.0935],
         [ 0.3506, -0.0238, -0.3993,  1.3271,  0.4323],
         [ 0.3090, -1.2232,  2.1694,  0.8107,  0.6668]],

        [[ 0.3763,  0.2427,  1.0556, -1.1662, -0.4858],
         [-0.4933, -0.0989,  0.9258, -0.5643,  0.7524],
         [ 0.2037,  0.0905,  0.4423, -0.5992,  1.6125],
         [-1.3971, -0.4179, -1.7167, -0.6007, -0.6098]]])
tensor a[1]:
tensor([[ 0.7786,  0.7285, -0.5888,  2.0147,  0.5040],
        [-0.3154, -0.8790,  0.4210,  1.9096, -0.0935],
        [ 0.3506, -0.0238, -0.3993,  1.3271,  0.4323],
        [ 0.3090, -1.2232,  2.1694,  0.8107,  0.6668]])
tensor a[1:, 2:4]:
tensor([[[ 0.3506, -0.0238, -0.3993,  1.3271,  0.432

### Yêu cầu:
- Cho biết shape của a[1] và a[1:, 2:4].
- Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

- a[1].shape = [4,5], a[1:, 2:4] = [2,2,5]
- note:
        a[1]       # Indexing
        a[1:3]     # Slicing
        a[-2:]     # Slicing

In [33]:
print(a[:,:,-2:])

tensor([[[-1.3565,  1.8896],
         [-0.0621,  0.3259],
         [ 1.0972, -1.5246],
         [-1.7583,  1.5572]],

        [[ 2.0147,  0.5040],
         [ 1.9096, -0.0935],
         [ 1.3271,  0.4323],
         [ 0.8107,  0.6668]],

        [[-1.1662, -0.4858],
         [-0.5643,  0.7524],
         [-0.5992,  1.6125],
         [-0.6007, -0.6098]]])


## Bài 5. Reshape và Flatten
### Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [35]:
import torch
a = torch.randn(3, 4)
print("original:")
print(a)
print("\nFlatten: ")
print(a.ravel())
print("\nReshape to 3 x 2 x 2: ")
print(a.reshape(3,2,2))

original:
tensor([[ 0.6404, -1.0792, -1.6060,  0.8194],
        [ 0.6458, -1.7727,  1.2736, -1.4466],
        [-1.4139, -2.1120,  0.5440,  2.0597]])

Flatten: 
tensor([ 0.6404, -1.0792, -1.6060,  0.8194,  0.6458, -1.7727,  1.2736, -1.4466,
        -1.4139, -2.1120,  0.5440,  2.0597])

Reshape to 3 x 2 x 2: 
tensor([[[ 0.6404, -1.0792],
         [-1.6060,  0.8194]],

        [[ 0.6458, -1.7727],
         [ 1.2736, -1.4466]],

        [[-1.4139, -2.1120],
         [ 0.5440,  2.0597]]])


#### Yêu cầu:
- Kiểm tra số phần tử trước và sau khi reshape.
- Thử reshape Tensor thành kích thước 2 × 6.

#### Trả lời
-Số phần tử trước và sau khi reshape vẫn giống nhau là 12 phần tử. Reshape chỉ thay đổi shape/cách tổ chức dữ liệu, không làm thay đổi số lượng phần tử.

In [37]:
print("reshape to 2 x 6")
print(a.reshape(2,6))

reshape to 2 x 6
tensor([[ 0.6404, -1.0792, -1.6060,  0.8194,  0.6458, -1.7727],
        [ 1.2736, -1.4466, -1.4139, -2.1120,  0.5440,  2.0597]])


## Bài 6. Phép toán và nhân ma trận
### Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

In [39]:
import torch
a = torch.randn(2,3)
b = torch.randn(2,3)
print("a:")
print(a)
print("b:")
print(b)
print("\n a+b")
print(a+b)
print("\n a*b")
print(a*b)
print("\n a/b")
print(a/b)
print("\n a^2")
print(a**2)
print("\nMatrix multiplication: ")
print(a @ b.T)

a:
tensor([[ 0.7589, -0.4573, -2.2052],
        [-0.7820, -0.4173,  0.7698]])
b:
tensor([[ 0.1310, -1.3351,  0.4278],
        [-0.8825,  0.2706, -0.8418]])

 a+b
tensor([[ 0.8899, -1.7924, -1.7774],
        [-1.6646, -0.1467, -0.0720]])

 a*b
tensor([[ 0.0994,  0.6105, -0.9435],
        [ 0.6902, -0.1129, -0.6480]])

 a/b
tensor([[ 5.7940,  0.3425, -5.1543],
        [ 0.8861, -1.5422, -0.9145]])

 a^2
tensor([[0.5759, 0.2091, 4.8629],
        [0.6115, 0.1742, 0.5925]])

Matrix multiplication: 
tensor([[-0.2336,  1.0628],
        [ 0.7841, -0.0707]])


#### Yêu cầu:
- Phân biệt phép toán a * b với a @ b.T.
- Cho biết shape của kết quả a @ b.T.

#### trả lời
- a*b là nhân các phần tử cùng vị trí của 2 ma trận lại với nhau
-  a @ b.T là phép nhân ma trận, b có shape (2,3) nên b.T có shape (3,2). do đó (2,3) @ (3,2) có shape là (2,2)

## Bài 7. Các hàm thống kê trên Tensor
### Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

In [ ]:
import torch
a = torch.randn(3,4)
print("a")
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStanderd devitation")
print(torch.std(a, dim = 0))
print("\nCumulative sum: ")
print(torch.cumsum(a, dim =0))

a
tensor([[-0.2751,  0.5868,  0.4238,  0.9143],
        [-0.0265, -0.5192,  0.4323, -0.8776],
        [ 0.9571,  1.5396,  0.6858, -0.4000]])

Mean:
tensor([ 0.2185,  0.5357,  0.5140, -0.1211])

Standerd devitation
tensor([0.6516, 1.0304, 0.1489, 0.9279])

Cumulative sum: 
tensor([[-0.2751,  0.5868,  0.4238,  0.9143],
        [-0.3017,  0.0676,  0.8561,  0.0367],
        [ 0.6554,  1.6072,  1.5419, -0.3633]])


#### Yêu cầu:
- Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.

#### thực hiện và trả lời yêu cầu

In [45]:
print("a")
print(a)
print("\nMean:")
print(torch.mean(a, dim=1))
print("\nStanderd devitation")
print(torch.std(a, dim = 1))
print("\nCumulative sum: ")
print(torch.cumsum(a, dim =1))

a
tensor([[-0.2751,  0.5868,  0.4238,  0.9143],
        [-0.0265, -0.5192,  0.4323, -0.8776],
        [ 0.9571,  1.5396,  0.6858, -0.4000]])

Mean:
tensor([ 0.4124, -0.2478,  0.6956])

Standerd devitation
tensor([0.5017, 0.5720, 0.8126])

Cumulative sum: 
tensor([[-0.2751,  0.3117,  0.7355,  1.6498],
        [-0.0265, -0.5457, -0.1135, -0.9911],
        [ 0.9571,  2.4967,  3.1826,  2.7826]])


- dim =1 tính theo hàng cộng theo chiều trái sang phải
- dim =0 tính theo cột cộng theo chiều dọc từ trên xuống

## Bài 8. Autograd cơ bản
### Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

In [48]:
import torch
x = torch.tensor(3.6,requires_grad= True)
y = x*x
y.backward()
print("x=", x)
print("y=", y)
print("x.grad=", x.grad)

x= tensor(3.6000, requires_grad=True)
y= tensor(12.9600, grad_fn=<MulBackward0>)
x.grad= tensor(7.2000)


#### Yêu cầu:
- Tính thủ công đạo hàm của y = x2 tại x = 3.6 và so sánh với x.grad.
- Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.

#### trả lời
- tính thủ công với y = x^2 đạo hàm = 7.2 bằng x.grad 

In [50]:
import torch
x = torch.tensor(3.6,requires_grad= True)
y = 3*x**2 + 2*x + 1
y.backward()
print("x=", x)
print("y=", y)
print("x.grad=", x.grad)

x= tensor(3.6000, requires_grad=True)
y= tensor(47.0800, grad_fn=<AddBackward0>)
x.grad= tensor(23.6000)


## Bài 9. Gradient Descent tìm hệ số đa thức
### Sinh dữ liệu từ đa thức y = x^2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

In [55]:
import numpy as np
import torch

polynomial = np.poly1d([1,2,3]) # đa thứ thật y = x^2 + 2x + 3
N =20
X =np.random.randn(N, 1) * 5 # xin ngẫu nhiên 20 dữ liệu X 
Y = polynomial(X) # kết qua y qua tường X
XX = np.hstack( # np.hstack ghép theo chiều ngang
    [
        X*X,X,np.ones_like(X)
    ]
)
w = torch.randn(3, 1, requires_grad = True)
x = torch.tensor(XX,dtype=torch.float32)
y = torch.tensor(Y,dtype = torch.float32)

optimizer =torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:") # thấy hệ số ngẫu nhiên điểm xuất phát
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w # nhân 2 ma trận kết hợp x a b c lại cho ra dạng[ [a*x1² + b*x1 + c],[a*x2² + b*x2 + c],[a*x3² + b*x3 + c],...]
    mse = torch.mean(torch.square(y-y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 1.7570],
        [-0.6604],
        [ 1.0230]], requires_grad=True)
Learned coefficients:
tensor([[1.0108],
        [1.9685],
        [2.3661]], requires_grad=True)


#### Yêu cầu:
- So sánh ba hệ số học được với [1, 2, 3].
- Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().
#### trả lời
- hệ số học được là [1,0108,1.9685,2.3661] so với [1, 2, 3] lệch tới [0.0094,0.0020,1.0360]
- optimizer.zero_grad(): xóa đi gradient cũ để chuẩn bị tính gradient mới,xóa để tránh việc cộng dồn
-  mse.backward():Autograd tìm xem nên sửa a, b, c thế nào để sai số giảm xuống thật thấp
- optimizer.step(): khi biết được thông tin sửa thì optimizer.step() như người update lại a b c

## Bài 10. Giải hệ phương trình bằng Autograd
### Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

In [2]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 5000
optimizer = torch.optim.NAdam([A, B, C, D], lr = 0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A=",A)
print("B",B)
print("C",C)
print("D", D)

A= tensor(4.3363, requires_grad=True)
B tensor(4.6637, requires_grad=True)
C tensor(3.6637, requires_grad=True)
D tensor(2.6637, requires_grad=True)


#### Yêu cầu:
- Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.
- Nhận xét vì sao bài toán có thể có nhiều nghiệm.

- vô số nghiệm
- 